[package]
name = "backhand"
repository = "https://github.com/wcampbell0x2a/backhand"
version = "0.3.0"
edition = "2021"
rust-version = "1.60.0"
license = "MIT/Apache-2.0"
authors = ["wcampbell <wcampbell1995@gmail.com>"]
description = "Library for the reading, creating, and modification of SquashFS file systems"
keywords = ["filesystem", "deku", "squashfs", "linux"]
categories = ["filesystem", "parsing"]

[dependencies]
deku = "0.15.0"
flate2 = "1.0.24"
xz2 = "0.1.7"
clap = { version = "4.0.12", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }
thiserror = "1.0.37"
twox-hash = "1.6.3"

[dev-dependencies]
env_logger = "0.9.1"
test-log = { version = "0.2.11", features = ["trace"] }
test-assets = { git  = "https://github.com/wcampbell0x2a/test-assets", branch = "master" }
assert_cmd = { version = "2.0.7", features = ["color", "color-auto"] }
dir-diff = { git  = "https://github.com/wcampbell0x2a/dir-diff", branch = "add-checking-permissions" }
tempfile = "3.0.0"
